# Generated by Django 4.1.3 on 2022-12-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0002_shout_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shout',
            name='user',
        ),
    ]
